services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5432:5432"

  api-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
