services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - .:/appt
    ports:
      - "5433:5432"

  api-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/threatquery
